name: ci
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: |
            build --release
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create assets
        run: |
          cd target/release
          tar czvf replay_${RELEASE_VERSION}_x86_64-unknown-linux-gnu.tar.gz replay
          sha256sum replay_${RELEASE_VERSION}_x86_64-unknown-linux-gnu.tar.gz > replay_${RELEASE_VERSION}_x86_64-unknown-linux-gnu.tar.gz.sha256
      - name: Upload assets
        run: |
          cd target/release
          for ext in tar.gz tar.gz.sha256; do
            export FILE=replay_${{ env.RELEASE_VERSION }}_x86_64-unknown-linux-gnu.$ext
            fluentci run --wasm github release_upload $TAG $FILE
          done
        env:
          TAG: ${{ env.RELEASE_VERSION }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
